spring:

    application:
        name: FoodDesigner

    datasource:
        url: jdbc:postgresql://localhost:5432/food_designer
        username: postgres
        password: 1

    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: create-drop
                format_sql: true
        show-sql: true
